language: node_js
node_js:
  - "8.11.2"
script:
  - cd packages/cyphfell && yarn install && sh ./test/test.sh
  - cd packages/cyphfell-test-app && yarn install && cd ../cyphfell && yarn install && sh ./test-automation/run.sh